print ("Hello World!!!!!!?????")
print("Gustavo")
print ("Novo usuario")
print("Bardao-do-Esmaga!!!")
print("To maluco")
print("Doce de leite")
print("Bardao-do-Esmaga!!!")
print("Commit do 20!!!")
print("Uma viagem para o futuro")
print("Gustavo")
printf("To ficando maluco")
print("Olá, meu nome é Camille")