print ("Hello World!!!!!!?????")
print("Víctor")
print ("Novo usuario")
<<<<<<< HEAD
=======
print("Bardao-do-Esmaga!!!")
print("Primeval Current - Albert")
print("To maluco")
print("Doce de leite")
print("Bardao-do-Esmaga!!!")
print("Commit do 20!!!")
print("Uma viagem para o futuro")
print("Hello, how are you?")
print("Gustavo")
print("To ficando maluco")
print("To ficando maluco")
print("Olá, meu nome é Camille")
print("AUauRaul")
print("Gustavo")
print("To ficando maluco")
print("Kelly aquiiii")
